<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\Facades\DebugRenderer;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\View;
use ArmoredCore\WebObjects\Post;
use ArmoredCore\WebObjects\Data;

?>

<html>

<head>
    <title>BANIDO!</title>
</head>
<body>
    <div class="texto">
        <p>ESTÁ BANIDO DESTE SITE!</p>
    </div>
</body>

</html>