<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\Facades\DebugRenderer;
use ArmoredCore\WebObjects\URL;

?>

<script>
    var bleep = new Audio();
    bleep.src = "diceThrow1.wav"
</script>

<html>

<head>
    <title>Shut the Box!</title>
    <link rel="stylesheet" href="../../../public/css/Tabuleiro.css">
</head>
<body>
    <div class="pecasdireita">
        <button class="butao">1</button>
        <button class="butao">2</button>
        <button class="butao">3</button>
        <button class="butao">4</button>
        <button class="butao">5</button>
        <button class="butao">6</button>
        <button class="butao">7</button>
        <button class="butao">8</button>
        <button class="butao">9</button>
    </div>

    <div class="pecasesquerda">
        <button class="butao">1</button>
        <button class="butao">2</button>
        <button class="butao">3</button>
        <button class="butao">4</button>
        <button class="butao">5</button>
        <button class="butao">6</button>
        <button class="butao">7</button>
        <button class="butao">8</button>
        <button class="butao">9</button>
    </div>

    <div class="tabuleiro">

    </div>

</body>

</html>